services:
    web:
        image: trafex/php-nginx:latest
        ports:
            - "80:8080"
        volumes:
            -   type: bind
                source: /media/Gonzales/00_symfony/web
                target: /var/www/html
    db:
        image: mariadb:latest
        restart: always
#        ports:
#            - "3306:3309"
        environment:
            MARIADB_ROOT_PASSWORD: root
        volumes:
            - type: bind
              source: /media/Gonzales/00_symfony/data/db
              target: /var/lib/mysql
