services:
    web:
        build: build/.
        ports:
            - "80:8080"
        volumes:
            - type: bind
              source: ../web
              target: /var/www/html
# currently copied during build. you can opt to mount it instead
#            - type: bind
#              source: /media/Gonzales/00_symfony/docker/nginx/nginx.conf
#              target: /etc/nginx/conf.d/symfony-web-root.conf

    db:
        image: mariadb:latest
        restart: always
#        ports:
#            - "3306:3309"
        environment:
            MARIADB_ROOT_PASSWORD: root
        volumes:
            - type: bind
              source: ../data/db
              target: /var/lib/mysql
